name: Build and push Docker image to GHCR

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Get latest tag
        id: get-latest-tag
        uses: actions/github-script@v4
        with:
          script: |
            const tags = await github.repos.listTags({
              owner: context.repo.owner,
              repo: context.repo.repo
            });
            const latestTag = tags.data[0].name;
            console.log(`Latest tag: ${latestTag}`);
            return { latestTag: latestTag };
          secrets: |
            GITHUB_TOKEN

      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ghcr.io/fileshare:latest
            ghcr.io/fileshare:$${{ steps.get-latest-tag.outputs.latest-tag }}
