name: Docker latest image

on:
  release:
    types: [created]

jobs:
  Deploy-latest:
    if: ${{ github.event_name == 'release' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        
      - name: Set date
        run: echo "DATE=$(date +%Y-%m-%d)" >> $GITHUB_ENV

      - name: Build and push latest release
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: | 
            ghcr.io/toomas633/fileshare:${{ github.event.release.tag_name }}
            ghcr.io/toomas633/fileshare:latest
            docker.io/toomas633/fileshare:${{ github.event.release.tag_name }}
            docker.io/toomas633/fileshare:latest
          labels: |
            org.opencontainers.image.created=${{ env.DATE }}
            org.opencontainers.image.version=${{ github.event.release.tag_name }}