name: SonarCloud

on:
  push:
    branches:
      - update
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  pull-requests: read

jobs:
  Analyze:
    runs-on: ubuntu-latest
    steps:
#      - name: Checkout
#        uses: actions/checkout@v3
#        with:
#          fetch-depth: 0
#
#      - name: Setup PHP with Xdebug
#        uses: shivammathur/setup-php@v2
#        with:
#          php-version: '8.1'
#          coverage: xdebug
#            
#      - name: Install dependencies with composer
#        run: composer update --no-ansi --no-interaction --no-progress

      - name: Analyze with SonarCloud
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args:
            -Dsonar.projectKey=Toomas633_FileShare
            -Dsonar.organization=toomas633
            #-Dsonar.tests= # optional. For more info about Code Coverage, please refer to https://docs.sonarcloud.io/enriching/test-coverage/overview/