name: SonarCloud

on:
  push:
    branches:
      - update
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  pull-requests: read

jobs:
  Analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3
          
      - name: Install tox and any other packages
        run: pip install tox datetime pytz

      - name: Run tox
        run: tox -e py

      - name: Analyze with SonarCloud
        uses: SonarSource/sonarcloud-github-action@de2e56b42aa84d0b1c5b622644ac17e505c9a049
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args:
            -Dsonar.projectKey=Toomas633_FileShare
            -Dsonar.organization=toomas633
            #-Dsonar.tests= # optional. For more info about Code Coverage, please refer to https://docs.sonarcloud.io/enriching/test-coverage/overview/